### ISSUE TITLE
Issue with online text and file submission 

### ISSUE THREAD

**Issue by kristian-94** [catalyst/moodle-fileconverter_librelambda#8]
When submitting online text plus a file in the same submission, we see a blank page and the converted file document on page 2 of 2. We also don't see the online text in the converted PDF. 

We should see the two documents both converted and appended to eachother in the PDF one after the other as we do with unoconv.

**Comment by golenkovm** [comment]
After my investigation I can state that the root of the issue - converter.

Online text submission is stored as HTML file. When it goes to converter it comes back with blank first page and partially missing content.

Here is an example:
- check submission html file content:
```
root@ab9da02fa0d4:/var/lib/sitedata# cat filedir/2e/c4/2ec4be54e14eff9b8d8c0751be8e025d6ad6cc0d 
<!DOCTYPE html>
<html><head><meta charset="UTF-8"></head><body><p>aaaaa</p><p>bbbbb</p></body></html>
```
- upload html file to input bucket with https://github.com/catalyst/moodle-fileconverter_librelambda/blob/master/classes/converter.php#L341
- catch the pdf in output bucket and confirm that it has blank first page and the content is partially missing:
![image](https://user-images.githubusercontent.com/22066290/65933541-368bde80-e455-11e9-968e-c1164b97e7c3.png)

**Comment by golenkovm** [comment]
`--writer` key should be added to https://github.com/catalyst/moodle-fileconverter_librelambda/blob/master/lambda/lambdaconvert.py#L91 in order to use `writer_pdf_Export` filter with html->pdf convertation. According my tests it won't affect other convertations:

`html` => Command with `--writer` key uses `writer_pdf_Export` filter and converts files properly, while command without this flag uses `writer_web_pdf_Export`.

`doc`  => Both commands are using `writer_pdf_Export` filter.
`docx` => Both commands are using `writer_pdf_Export` filter.
`rtf`  => Both commands are using `writer_pdf_Export` filter.
`xls`  => Both commands are using `calc_pdf_Export` filter.
`xlsx` => Both commands are using `calc_pdf_Export` filter.
`ppt`  => Both commands are using `impress_pdf_Export` filter.
`pptx` => Both commands are using `impress_pdf_Export` filter.
`odt`  => Both commands are using `writer_pdf_Export` filter.
`ods`  => Both commands are using `calc_pdf_Export` filter.
`png`  => Both commands are using `draw_pdf_Export` filter.
`jpg`  => Both commands are using `draw_pdf_Export` filter.
`txt`  => Both commands are using `writer_pdf_Export` filter.
`gif`  => Both commands are using `draw_pdf_Export` filter.

**Comment by golenkovm** [comment]
Fixed by merging https://github.com/catalyst/moodle-fileconverter_librelambda/pull/9 into master branch.
Lambda script https://github.com/catalyst/moodle-fileconverter_librelambda/blob/master/lambda/lambdaconvert.zip needs to be updated on AWS Lambda side.

**Comment by kristian-94** [comment]
Thank you for your work misha :)
